public enum Figure {

    TRIANGLE, RECTANGLE, TRAPEZOID, PARALLELOGRAM, RHOMBUS, ROUND, CIRCLE, RING, CYLINDER, CONE, CUT_CONE,
    CUBE, RECTANGULAR_BOX, PYRAMID, RECTANGULAR_TRIANGLE, ISOSCELES_TRAPEZOID, ISOSCELES_TRIANGLE

}
